### ISSUE TITLE
Example Sheet...

### ISSUE THREAD

**Issue by bonelifer** [cunla/gsheets-report#1]
Could you provide an example sheet. Just trying to piece together something with no real knowledge of python. So far I've found a script to get my weight from my Etekcity ESF24 scale(hopefully I find an easy enough google py api wrapper). Just need to know what format this script expects the sheet data to be entered as.

**Comment by cunla** [comment]
Will do

**Comment by cunla** [comment]
Updated `settings.py` to point to https://docs.google.com/spreadsheets/d/1fbFXa0zeedpnF0M0gfoZTjgzORU9db8Vj9D6LmGt2ZM/edit#gid=0

**Comment by bonelifer** [comment]
Thanks.
